name: UserControl
load: STARTUP
main: no.runsafe.UserControl.Plugin
version: 1.0
authors: [mortenn]
depend: []
description: Tools for handling users
commands:
  usercontrol:
    description: Administrativ features