name: UserControl
main: no.runsafe.UserControl.Plugin
version: 1.1.@BUILD@
authors: [mortenn]
depend: []
description: Tools for handling users
commands:
  ban:
    description: Ban a user from the server permanently
  tempban:
    description: Ban a user from the server for a given time period
  unban:
    description: Lift a temporary or permanent ban for a user
  kick:
    description: Kick a user from the server
  kickall:
    description: Kick all users from the server
  sudo:
    description: Make a user run a command
  banip:
    description: Ban an IP address from the server permanently
  unbanip:
    description: Lift a permanent ban from an IP-address
  seen:
    description: Gives information of when a user was last on the server
  whois:
    description: Queries the server about a player, printing available information.
  op:
    description: Makes a player an operator.
  deop:
    description: Revokes a players status as an operator
  setredirectlocation:
    description: Sets the location to redirect players to on login.
  removeredirectlocation:
    description: Removes the re-direction location.
  setfirstspawn:
    description: Sets the first-join spawn point
  played:
    description: Tells you how much time you have spent on the server
  maintenance:
    description: Toggles the servers current maintenance state.
  rank:
    description: Allows you to set a players rank.
  list:
    description: List online players
  uuidscan:
    description: Try to update players with UUIDs in the database.