name: UserControl
main: no.runsafe.UserControl.Plugin
version: 1.0.@BUILD@
authors: [mortenn]
depend: []
description: Tools for handling users
commands:
  usercontrol:
    description: Administrative features
  ban:
    description: Ban a user from the server permanently
  tempban:
    description: Ban a user from the server for a given time period
  unban:
    description: Lift a temporary or permanent ban for a user
  kick:
    description: Kick a user from the server
  kickall:
    description: Kick all users from the server
  sudo:
    description: Make a user run a command
  banip:
    description: Ban an IP address from the server permanently
  unbanip:
    description: Lift a permanent ban from an IP-address
  seen:
    description: Gives information of when a user was last on the server
  whois:
    description: Queries the server about a player, printing available information.
  op:
    description: Makes a player an operator.
  deop:
    description: Revokes a players status as an operator